### ISSUE TITLE
How to check iOS verison

### ISSUE THREAD

**Issue by cliren** [infinum/iOS-prince-of-versions#12]
The android library has minimum_version_min_sdk to check agains min Android SDK supported. Is there a similar support for iOS to check against a particular iOS version say "min_ios_version:9.0"?

**Comment by EfrenPerez94** [comment]
If you are talking about what kind of devices support the application you can open the Xcode project and in the left side you will see the name of the project with their icon, so if you click on this  you will get all the information related to the project configuration, scroll down and you will find the deployment info, here you can check the iOS version for the project.

In the other hand if you are talking about the pod file you can specify the platform using the following lines of code

`  "platforms": {
    "ios": "8.0"
  },`

**Comment by fgulan** [comment]
minimum_version_min_sdk is also used on iOS as well, just put "minimum_version_min_sdk' : "9.0" for iOS 9.
