### ISSUE TITLE
Add `ON_APP_START` Type to `notify_last_version_frequency`

### ISSUE THREAD

**Issue by Filip2Stojanovski** [infinum/ios-prince-of-versions#50]
Currently, the `PrinceOfVersions` library allows developers to set the `notify_last_version_frequency` in the JSON configuration to values like `ALWAYS` or `ONCE`. 
However, there is no option to notify users about a new version only on each app start. This feature would be particularly useful for scenarios where developers want to ensure that users are informed about a new version every time the app is launched, but without showing the notification more than once per session.

The change should be fairly simple, something like:
`let shouldNotify = !latestVersion.wasNotified || updateInfoData.notificationType == .always || (updateInfoData.notificationType == .onAppStart && !latestVersion.wasNotifiedOnAppStart)`

```
public var wasNotifiedOnAppStart: Bool {
        return UserDefaults.standard.bool(forKey: "wasNotifiedOnAppStart")
}
```

```
@objc public func markNotifiedOnAppStart() {
        UserDefaults.standard.set(true, forKey: "wasNotifiedOnAppStart")
}
```
It is important to reset this `wasNotifiedOnAppStart` flag to `false` within `application(_:didFinishLaunchingWithOptions:)` method to ensure the correct behaviour.

**Comment by jabou** [comment]
Hi @Filip2Stojanovski ,

Thank you for the proposal! 

If this type is added, we are fully relying on the user to reset that flag inside the `application(_:didFinishLaunchingWithOptions:)` (as you mentioned). Additionally, we would have to introduce a similar requirement for Android as well.
If we do that, and the user forgets to reset that flag, you'll have the same behavior as if you would use `ALWAYS`.

By using the `ALWAYS` type, you are entirely in control when you want to show that info. E.g., you can implement that same flag and keep tracking if info was shown on active session once or multiple times. Another approach is to implement PoV check within `application(_:didFinishLaunchingWithOptions:)`, that way even if you have set `ALWAYS`, user will get the message only on app startup.

Is this something you can work with?

**Comment by Filip2Stojanovski** [comment]
Hi @jabou,

Yes, I end up using `ALWAYS` type with the same logic that I wrote in my comment. I didn't do PoV check within `application(_:didFinishLaunchingWithOptions:)` since it was easier for me to do it in a particular screen, but I see how that can be achieved as well.

Thank you, and since there is no need of implementing this change I will close the issue.
